config/routes.rb
Rails.application.routes.draw do

  root :to => 'diary_entries#index'

  resources :options

  resources :actions

  resources :reasons

  resources :feelings

  resources :diary_entries

  resources :contents

end

app/models/feeling.rb
class Feeling < ActiveRecord::Base
  attr_accessor :key

  has_many :options

  def key
    "I feel"
  end

end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :set_feeling, only: [:show, :edit, :update, :destroy]

  # GET /feelings
  # GET /feelings.json
  def index
    @feelings = Feeling.all
  end

  # GET /feelings/1
  # GET /feelings/1.json
  def show
  end

  # GET /feelings/new
  def new
    @feeling = Feeling.new
  end

  # GET /feelings/1/edit
  def edit
  end

  # POST /feelings
  # POST /feelings.json
  def create
    @feeling = Feeling.new(feeling_params)

    respond_to do |format|
      if @feeling.save
        format.html { redirect_to @feeling, notice: 'Feeling was successfully created.' }
        format.json { render :show, status: :created, location: @feeling }
      else
        format.html { render :new }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feelings/1
  # PATCH/PUT /feelings/1.json
  def update
    respond_to do |format|
      if @feeling.update(feeling_params)
        format.html { redirect_to @feeling, notice: 'Feeling was successfully updated.' }
        format.json { render :show, status: :ok, location: @feeling }
      else
        format.html { render :edit }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feelings/1
  # DELETE /feelings/1.json
  def destroy
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to feelings_url, notice: 'Feeling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feeling
      @feeling = Feeling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feeling_params
      params.require(:feeling).permit(:options, :key)
    end
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_form.html.erb
<%= form_for(@feeling) do |f| %>
  <% if @feeling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feeling.errors.count, "error") %> prohibited this feeling from being saved:</h2>

      <ul>
      <% @feeling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_field :options %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feelings/edit.html.erb
<h1>Editing feeling</h1>

<%= render 'form' %>

<%= link_to 'Show', @feeling %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/index.html.erb
<h1>Listing feelings</h1>

<table>
  <thead>
    <tr>
      <th>Options</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feelings.each do |feeling| %>
      <tr>
        <td><%= feeling.options %></td>
        <td><%= feeling.key %></td>
        <td><%= link_to 'Show', feeling %></td>
        <td><%= link_to 'Edit', edit_feeling_path(feeling) %></td>
        <td><%= link_to 'Destroy', feeling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feeling', new_feeling_path %>

app/views/feelings/new.html.erb
<h1>New feeling</h1>

<%= render 'form' %>

<%= link_to 'Back', feelings_path %>

app/views/feelings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Options:</strong>
  <%= @feeling.options %>
</p>

<p>
  <strong>Key:</strong>
  <%= @feeling.key %>
</p>

<%= link_to 'Edit', edit_feeling_path(@feeling) %> |
<%= link_to 'Back', feelings_path %>