config/routes.rb
Rails.application.routes.draw do

  root :to => 'diary_entries#index'

  resources :options

  resources :actions

  resources :reasons

  resources :feelings

  resources :diary_entries

  resources :contents

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_action, only: [:show, :edit, :update, :destroy]

  # GET /actions
  # GET /actions.json
  def index
    @actions = Action.all
  end

  # GET /actions/1
  # GET /actions/1.json
  def show
  end

  # GET /actions/new
  def new
    @action = Action.new
  end

  # GET /actions/1/edit
  def edit
  end

  # POST /actions
  # POST /actions.json
  def create
    @action = Action.new(action_params)

    respond_to do |format|
      if @action.save
        format.html { redirect_to @action, notice: 'Action was successfully created.' }
        format.json { render :show, status: :created, location: @action }
      else
        format.html { render :new }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actions/1
  # PATCH/PUT /actions/1.json
  def update
    respond_to do |format|
      if @action.update(action_params)
        format.html { redirect_to @action, notice: 'Action was successfully updated.' }
        format.json { render :show, status: :ok, location: @action }
      else
        format.html { render :edit }
        format.json { render json: @action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actions/1
  # DELETE /actions/1.json
  def destroy
    @action.destroy
    respond_to do |format|
      format.html { redirect_to actions_url, notice: 'Action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action
      @action = Action.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_params
      params.require(:action).permit(:options, :key)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/_form.html.erb
<%= form_for(@action) do |f| %>
  <% if @action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action.errors.count, "error") %> prohibited this action from being saved:</h2>

      <ul>
      <% @action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_field :options %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actions/edit.html.erb
<h1>Editing action</h1>

<%= render 'form' %>

<%= link_to 'Show', @action %> |
<%= link_to 'Back', actions_path %>

app/views/actions/index.html.erb
<h1>Listing actions</h1>

<table>
  <thead>
    <tr>
      <th>Options</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actions.each do |action| %>
      <tr>
        <td><%= action.options %></td>
        <td><%= action.key %></td>
        <td><%= link_to 'Show', action %></td>
        <td><%= link_to 'Edit', edit_action_path(action) %></td>
        <td><%= link_to 'Destroy', action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action', new_action_path %>

app/views/actions/new.html.erb
<h1>New action</h1>

<%= render 'form' %>

<%= link_to 'Back', actions_path %>

app/views/actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Options:</strong>
  <%= @action.options %>
</p>

<p>
  <strong>Key:</strong>
  <%= @action.key %>
</p>

<%= link_to 'Edit', edit_action_path(@action) %> |
<%= link_to 'Back', actions_path %>