config/routes.rb
Rails.application.routes.draw do

  root :to => 'diary_entries#index'

  resources :options

  resources :actions

  resources :reasons

  resources :feelings

  resources :diary_entries

  resources :contents

end

app/models/reason.rb
class Reason < ActiveRecord::Base
  attr_accessor :key

  has_many :options

  def key
    "because"
  end

end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:options, :key)
    end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<%= form_for(@reason) do |f| %>
  <% if @reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
      <% @reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_field :options %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<h1>Editing reason</h1>

<%= render 'form' %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Back', reasons_path %>

app/views/reasons/index.html.erb
<h1>Listing reasons</h1>

<table>
  <thead>
    <tr>
      <th>Options</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
      <tr>
        <td><%= reason.options %></td>
        <td><%= reason.key %></td>
        <td><%= link_to 'Show', reason %></td>
        <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
        <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reason', new_reason_path %>

app/views/reasons/new.html.erb
<h1>New reason</h1>

<%= render 'form' %>

<%= link_to 'Back', reasons_path %>

app/views/reasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Options:</strong>
  <%= @reason.options %>
</p>

<p>
  <strong>Key:</strong>
  <%= @reason.key %>
</p>

<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>